import { Request, Invoice, TrackingInfo, DashboardStats } from '@/types';

export const mockRequests: Request[] = [
  {
    id: 'REQ-2025-001',
    clientName: 'John Anderson',
    clientEmail: 'john@example.com',
    clientPhone: '+1-555-0123',
    itemName: 'Electronics Components',
    itemDescription: 'Microcontrollers and sensors for manufacturing',
    quantity: 500,
    weight: 25,
    originCountry: 'China',
    destinationCountry: 'United States',
    purpose: 'import',
    status: 'payment_confirmed',
    createdAt: new Date('2025-10-01'),
    updatedAt: new Date('2025-10-08'),
  },
  {
    id: 'REQ-2025-002',
    clientName: 'Sarah Mitchell',
    clientEmail: 'sarah@company.com',
    clientPhone: '+1-555-0124',
    itemName: 'Textile Materials',
    itemDescription: 'Cotton fabric rolls for garment production',
    quantity: 200,
    weight: 150,
    originCountry: 'India',
    destinationCountry: 'United Kingdom',
    purpose: 'import',
    status: 'in_transit',
    createdAt: new Date('2025-09-25'),
    updatedAt: new Date('2025-10-10'),
  },
  {
    id: 'REQ-2025-003',
    clientName: 'Michael Chen',
    clientEmail: 'mchen@business.com',
    clientPhone: '+1-555-0125',
    itemName: 'Coffee Beans',
    itemDescription: 'Premium Arabica coffee beans',
    quantity: 1000,
    weight: 500,
    originCountry: 'Colombia',
    destinationCountry: 'Japan',
    purpose: 'export',
    status: 'under_review',
    createdAt: new Date('2025-10-10'),
    updatedAt: new Date('2025-10-11'),
  },
  {
    id: 'REQ-2025-004',
    clientName: 'Emma Wilson',
    clientEmail: 'ewilson@mail.com',
    clientPhone: '+1-555-0126',
    itemName: 'Medical Equipment',
    itemDescription: 'Diagnostic devices and supplies',
    quantity: 50,
    weight: 75,
    originCountry: 'Germany',
    destinationCountry: 'Canada',
    purpose: 'import',
    status: 'invoice_sent',
    createdAt: new Date('2025-10-05'),
    updatedAt: new Date('2025-10-09'),
  },
  {
    id: 'REQ-2025-005',
    clientName: 'David Park',
    clientEmail: 'dpark@enterprise.com',
    clientPhone: '+1-555-0127',
    itemName: 'Industrial Machinery Parts',
    itemDescription: 'Replacement parts for manufacturing equipment',
    quantity: 100,
    weight: 200,
    originCountry: 'South Korea',
    destinationCountry: 'Mexico',
    purpose: 'export',
    status: 'pending',
    createdAt: new Date('2025-10-12'),
    updatedAt: new Date('2025-10-12'),
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: 'INV-001',
    requestId: 'REQ-2025-001',
    invoiceNumber: 'INV-2025-001',
    clientName: 'John Anderson',
    clientEmail: 'john@example.com',
    itemDescription: 'Electronics Components - Microcontrollers and sensors',
    shippingCost: 450,
    customsDuties: 275,
    handlingFee: 150,
    insurance: 100,
    documentationFee: 75,
    serviceFee: 200,
    subtotal: 1250,
    tax: 125,
    total: 1375,
    currency: 'USD',
    createdAt: new Date('2025-10-05'),
    status: 'paid',
  },
  {
    id: 'INV-002',
    requestId: 'REQ-2025-004',
    invoiceNumber: 'INV-2025-002',
    clientName: 'Emma Wilson',
    clientEmail: 'ewilson@mail.com',
    itemDescription: 'Medical Equipment - Diagnostic devices',
    shippingCost: 800,
    customsDuties: 450,
    handlingFee: 200,
    insurance: 300,
    documentationFee: 100,
    serviceFee: 350,
    subtotal: 2200,
    tax: 220,
    total: 2420,
    currency: 'USD',
    createdAt: new Date('2025-10-09'),
    status: 'sent',
  },
];

export const mockTracking: TrackingInfo[] = [
  {
    trackingId: 'TRK-2025-00001',
    requestId: 'REQ-2025-001',
    currentStage: 'international_transit',
    clientName: 'John Anderson',
    itemDescription: 'Electronics Components',
    estimatedDelivery: new Date('2025-10-20'),
    stages: [
      {
        stage: 'order_placed',
        status: 'completed',
        date: new Date('2025-10-01'),
        location: 'Online',
        notes: 'Order successfully placed',
      },
      {
        stage: 'payment_confirmed',
        status: 'completed',
        date: new Date('2025-10-08'),
        location: 'Payment Gateway',
        notes: 'Payment received and confirmed',
      },
      {
        stage: 'documentation_progress',
        status: 'completed',
        date: new Date('2025-10-09'),
        location: 'Office',
        notes: 'All documents prepared and verified',
      },
      {
        stage: 'ready_for_shipment',
        status: 'completed',
        date: new Date('2025-10-10'),
        location: 'Shenzhen, China',
        notes: 'Item collected and packaged',
      },
      {
        stage: 'in_transit_origin',
        status: 'completed',
        date: new Date('2025-10-11'),
        location: 'Shenzhen Port',
        notes: 'In transit to port',
      },
      {
        stage: 'customs_origin',
        status: 'completed',
        date: new Date('2025-10-12'),
        location: 'Shenzhen Customs',
        notes: 'Cleared customs successfully',
      },
      {
        stage: 'international_transit',
        status: 'current',
        date: new Date('2025-10-13'),
        location: 'Pacific Ocean',
        notes: 'In transit to destination country',
      },
      {
        stage: 'arrived_destination',
        status: 'pending',
      },
      {
        stage: 'customs_destination',
        status: 'pending',
      },
      {
        stage: 'out_for_delivery',
        status: 'pending',
      },
      {
        stage: 'delivered',
        status: 'pending',
      },
    ],
  },
  {
    trackingId: 'TRK-2025-00002',
    requestId: 'REQ-2025-002',
    currentStage: 'customs_destination',
    clientName: 'Sarah Mitchell',
    itemDescription: 'Textile Materials',
    estimatedDelivery: new Date('2025-10-18'),
    stages: [
      {
        stage: 'order_placed',
        status: 'completed',
        date: new Date('2025-09-25'),
      },
      {
        stage: 'payment_confirmed',
        status: 'completed',
        date: new Date('2025-09-28'),
      },
      {
        stage: 'documentation_progress',
        status: 'completed',
        date: new Date('2025-09-29'),
      },
      {
        stage: 'ready_for_shipment',
        status: 'completed',
        date: new Date('2025-10-01'),
      },
      {
        stage: 'in_transit_origin',
        status: 'completed',
        date: new Date('2025-10-02'),
      },
      {
        stage: 'customs_origin',
        status: 'completed',
        date: new Date('2025-10-03'),
      },
      {
        stage: 'international_transit',
        status: 'completed',
        date: new Date('2025-10-08'),
      },
      {
        stage: 'arrived_destination',
        status: 'completed',
        date: new Date('2025-10-15'),
        location: 'London Heathrow',
      },
      {
        stage: 'customs_destination',
        status: 'current',
        date: new Date('2025-10-16'),
        location: 'UK Customs',
        notes: 'Undergoing customs inspection',
      },
      {
        stage: 'out_for_delivery',
        status: 'pending',
      },
      {
        stage: 'delivered',
        status: 'pending',
      },
    ],
  },
];

export const mockDashboardStats: DashboardStats = {
  totalRequests: 47,
  pendingRequests: 8,
  activeShipments: 12,
  completedDeliveries: 35,
  totalRevenue: 87450,
  monthlyRevenue: 12840,
};